<?php

// Onboarding guide (v3.02): English edition, mirrors lang/de/onboarding.php.
return [
    'steps' => [
        ['title' => 'Welcome', 'body' => 'This guide walks you through all areas of the platform in a few minutes. Use "Next" to browse the topics; each topic links directly to the matching module. Detailed descriptions are always available under Help & FAQ and in the knowledge base (user manual, process guide).', 'route' => null],
        ['title' => 'Login & Security', 'body' => 'Log in with e-mail and password. Two-factor authentication is mandatory for internal roles, investors and advisory board members: at first login you scan a QR code with an authenticator app and receive recovery codes (shown once, keep them safe). Language DE/EN at the top right, change your password under Settings.', 'route' => 'profile.edit'],
        ['title' => 'Navigation', 'body' => 'The grouped main navigation is on the left (Operations, Sales & Clients, Treasury & Finance, Governance & Oversight). Top right: Administration (users, integrations, changelog), the language switcher and logout. You only see the areas your role may use; access is additionally enforced server-side.', 'route' => null],
        ['title' => 'Clients & CRM', 'body' => 'New medical clients start in the CRM (lead → opportunity) and go through onboarding with the KYC review (identification, beneficial owners, PEP screening, register check, creditworthiness). On the client detail page you maintain the industry segment, B2B/B2C and the internal rating (AAA–C); the rating drives the fee surcharge at purchase.', 'route' => 'organizations.index'],
        ['title' => 'Receivables & Purchase', 'body' => 'Clients submit receivables in the client portal. Internally this is followed by the formal review, the automated risk/limit check and the purchase calculation (payout, security retention, fee including the rating surcharge). The second approval must be given by a DIFFERENT person; the four-eyes principle is technically enforced.', 'route' => 'receivables.index'],
        ['title' => 'Escalation (front/back office)', 'body' => 'If a receivable is rejected, the front office can request a second vote from the back office with a written justification. If the back office rejects, the executive board decides definitively. Each stage is recorded tamper-evidently with person, timestamp and justification.', 'route' => null],
        ['title' => 'Payouts & Incoming Payments', 'body' => 'Treasury bundles approved purchases into payout batches (first and second approval, SEPA export, bank confirmation). Incoming payments are matched to receivables, including partial payments; after full payment the settlement releases the retention.', 'route' => 'payments.index'],
        ['title' => 'Dunning & Default', 'body' => 'Overdue receivables are flagged automatically every day and appear in the dunning list. Cases: reminder, dispute, recourse, default (with loss write-off). Hand-over to debt collection via the prepared interface.', 'route' => 'dunning.index'],
        ['title' => 'Investors & Facilities', 'body' => 'Facilities with commitment, interest, ranking, special termination right and notice period. Terminations (ordinary, special termination, investor insolvency) are recorded with their reason. Investors see their investment, interest payments and clearly labelled model calculations in their own portal.', 'route' => 'facilities.index'],
        ['title' => 'Credit Lines & Insurance', 'body' => 'Purchase/payout lines and debtor limits are managed per client. Lines above the concentration risk threshold (default EUR 30,000) without insurance cover are flagged; for each line you maintain the insurer, insured amount and status.', 'route' => 'credit-lines.index'],
        ['title' => 'Reporting & Controlling', 'body' => 'Dashboards per role with charts, CSV/DATEV exports and KPI reports by e-mail (immediately or as a subscription). Controlling records costs by category for the executive board\'s profitability view.', 'route' => 'reports.index'],
        ['title' => 'Support & Administration', 'body' => 'Questions and requests go through the ticket system (Support menu). User administration (Administration, top right) creates accounts, credentials are sent by e-mail with a password set-up link, and maintains the personnel file including joining/leaving dates: accounts are only usable from the joining date and are locked automatically after leaving. The changelog shows all releases. You are ready to go!', 'route' => 'tickets.index'],
    ],
];
