<?php

// Onboarding-Leitfaden (v3.02): Schritte lokalisierbar, Deutsch ist die Referenzfassung.
// 'route' verweist auf den passenden Modul-Einstieg (null = kein Direktlink).
return [
    'steps' => [
        ['title' => 'Willkommen', 'body' => 'Dieser Leitfaden führt Sie in wenigen Minuten durch alle Bereiche der Plattform. Mit „Weiter" blättern Sie durch die Themen; jedes Thema verlinkt direkt in das passende Modul. Ausführliche Beschreibungen finden Sie jederzeit unter Hilfe & FAQ und in der Wissensdatenbank (Benutzerhandbuch, Prozessleitfaden).', 'route' => null],
        ['title' => 'Anmeldung & Sicherheit', 'body' => 'Login mit E-Mail und Passwort. Für interne Rollen, Investoren und Beiräte ist die Zwei-Faktor-Authentifizierung Pflicht: Beim ersten Login scannen Sie einen QR-Code mit einer Authenticator-App und erhalten Wiederherstellungscodes (einmalig angezeigt, sicher verwahren). Sprache DE/EN oben rechts, Passwort ändern unter Einstellungen.', 'route' => 'profile.edit'],
        ['title' => 'Navigation', 'body' => 'Links die gruppierte Hauptnavigation (Betrieb, Vertrieb & Kunden, Treasury & Finanzen, Steuerung & Aufsicht). Oben rechts: Administration (Benutzer, Integrationen, Changelog), Sprachumschalter und Abmelden. Sie sehen nur die Bereiche, die Ihre Rolle nutzen darf, der Zugriff ist zusätzlich serverseitig abgesichert.', 'route' => null],
        ['title' => 'Kunden & CRM', 'body' => 'Neue Mediziner-Kunden entstehen im CRM (Lead → Opportunity) und durchlaufen das Onboarding mit KYC-Prüfung (Identifikation, wirtschaftlich Berechtigte, PEP-Screening, Registerabgleich, Bonität). Auf der Kundendetailseite pflegen Sie Branchensegment, B2B/B2C und das interne Rating (AAA–C), das Rating steuert den Gebührenaufschlag beim Ankauf.', 'route' => 'organizations.index'],
        ['title' => 'Forderungen & Ankauf', 'body' => 'Kunden reichen Forderungen im Kundenportal ein. Intern folgen formale Prüfung, automatische Risiko-/Limitprüfung und die Ankaufsberechnung (Auszahlung, Sicherheitseinbehalt, Gebühr inkl. Rating-Aufschlag). Die Zweitfreigabe muss durch eine ANDERE Person erfolgen, Vier-Augen-Prinzip, technisch erzwungen.', 'route' => 'receivables.index'],
        ['title' => 'Eskalation (Markt/Marktfolge)', 'body' => 'Wird eine Forderung abgelehnt, kann der Markt mit Begründung ein Zweitvotum der Marktfolge anfordern. Lehnt die Marktfolge ab, entscheidet der Vorstand endgültig. Jede Stufe wird mit Person, Zeitstempel und Begründung revisionssicher protokolliert.', 'route' => null],
        ['title' => 'Auszahlungen & Zahlungseingänge', 'body' => 'Treasury bündelt freigegebene Ankäufe zu Auszahlungsbatches (Erst- und Zweitfreigabe, SEPA-Export, Bankbestätigung). Zahlungseingänge werden den Forderungen zugeordnet, auch Teilzahlungen; nach vollständiger Zahlung erfolgt die Abrechnung mit Reservefreigabe.', 'route' => 'payments.index'],
        ['title' => 'Mahnwesen & Ausfall', 'body' => 'Überfällige Forderungen werden täglich automatisch markiert und erscheinen in der Mahnliste. Fälle: Mahnung, Streitfall, Rückgriff, Ausfall (mit Verlust-Ausbuchung). Übergabe an Inkasso über die vorbereitete Schnittstelle.', 'route' => 'dunning.index'],
        ['title' => 'Investoren & Fazilitäten', 'body' => 'Fazilitäten mit Zusage, Zins, Rang, Sonderkündigungsrecht und Frist. Kündigungen (ordentlich, Sonderkündigung, Insolvenz des Investors) werden mit Grund protokolliert. Investoren sehen im eigenen Portal ihr Investment, Zinszahlungen und gekennzeichnete Modellrechnungen.', 'route' => 'facilities.index'],
        ['title' => 'Kreditlinien & Versicherung', 'body' => 'Je Kunde werden Ankaufs-/Auszahlungslinien und Debitorenlimits geführt. Linien über der Klumpenrisiko-Schwelle (Standard 30.000 EUR) ohne Versicherungsschutz werden markiert; je Linie pflegen Sie Versicherer, versicherte Summe und Status.', 'route' => 'credit-lines.index'],
        ['title' => 'Reporting & Controlling', 'body' => 'Dashboards je Rolle mit Diagrammen, CSV-/DATEV-Exporte und KPI-Reports per E-Mail (sofort oder als Abo). Controlling erfasst Kosten nach Kategorien für die Wirtschaftlichkeitssicht der Geschäftsleitung.', 'route' => 'reports.index'],
        ['title' => 'Support & Administration', 'body' => 'Fragen und Wünsche laufen über das Ticketsystem (Menü Support). Die Benutzerverwaltung (Administration oben rechts) legt Zugänge an, die Zugangsdaten gehen per E-Mail mit Passwort-Setz-Link, und pflegt die Personalakte inkl. Ein-/Austrittsdatum: Konten sind erst ab Eintritt nutzbar und nach Austritt automatisch gesperrt. Im Changelog sehen Sie alle Releases. Damit sind Sie startklar!', 'route' => 'tickets.index'],
    ],
];
